version: "3"
services:
  database:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - .env/development/database
  web:
    env_file:
      - .env/development/database
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - database
    links:
      - database
    
    # stdin_open: true
    # tty: true

